//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UpDown {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpDown.NumericUpDownSoap")]
    public interface NumericUpDownSoap {
        
        // CODEGEN: Generating message contract since element name tag from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Up", ReplyAction="*")]
        Web.UpDown.UpResponse Up(Web.UpDown.UpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Up", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.UpDown.UpResponse> UpAsync(Web.UpDown.UpRequest request);
        
        // CODEGEN: Generating message contract since element name tag from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Down", ReplyAction="*")]
        Web.UpDown.DownResponse Down(Web.UpDown.DownRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Down", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.UpDown.DownResponse> DownAsync(Web.UpDown.DownRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Up", Namespace="http://tempuri.org/", Order=0)]
        public Web.UpDown.UpRequestBody Body;
        
        public UpRequest() {
        }
        
        public UpRequest(Web.UpDown.UpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int current;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tag;
        
        public UpRequestBody() {
        }
        
        public UpRequestBody(int current, string tag) {
            this.current = current;
            this.tag = tag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.UpDown.UpResponseBody Body;
        
        public UpResponse() {
        }
        
        public UpResponse(Web.UpDown.UpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpResult;
        
        public UpResponseBody() {
        }
        
        public UpResponseBody(int UpResult) {
            this.UpResult = UpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Down", Namespace="http://tempuri.org/", Order=0)]
        public Web.UpDown.DownRequestBody Body;
        
        public DownRequest() {
        }
        
        public DownRequest(Web.UpDown.DownRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int current;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tag;
        
        public DownRequestBody() {
        }
        
        public DownRequestBody(int current, string tag) {
            this.current = current;
            this.tag = tag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.UpDown.DownResponseBody Body;
        
        public DownResponse() {
        }
        
        public DownResponse(Web.UpDown.DownResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownResult;
        
        public DownResponseBody() {
        }
        
        public DownResponseBody(int DownResult) {
            this.DownResult = DownResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NumericUpDownSoapChannel : Web.UpDown.NumericUpDownSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumericUpDownSoapClient : System.ServiceModel.ClientBase<Web.UpDown.NumericUpDownSoap>, Web.UpDown.NumericUpDownSoap {
        
        public NumericUpDownSoapClient() {
        }
        
        public NumericUpDownSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumericUpDownSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumericUpDownSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumericUpDownSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.UpDown.UpResponse Web.UpDown.NumericUpDownSoap.Up(Web.UpDown.UpRequest request) {
            return base.Channel.Up(request);
        }
        
        public int Up(int current, string tag) {
            Web.UpDown.UpRequest inValue = new Web.UpDown.UpRequest();
            inValue.Body = new Web.UpDown.UpRequestBody();
            inValue.Body.current = current;
            inValue.Body.tag = tag;
            Web.UpDown.UpResponse retVal = ((Web.UpDown.NumericUpDownSoap)(this)).Up(inValue);
            return retVal.Body.UpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.UpDown.UpResponse> Web.UpDown.NumericUpDownSoap.UpAsync(Web.UpDown.UpRequest request) {
            return base.Channel.UpAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.UpDown.UpResponse> UpAsync(int current, string tag) {
            Web.UpDown.UpRequest inValue = new Web.UpDown.UpRequest();
            inValue.Body = new Web.UpDown.UpRequestBody();
            inValue.Body.current = current;
            inValue.Body.tag = tag;
            return ((Web.UpDown.NumericUpDownSoap)(this)).UpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.UpDown.DownResponse Web.UpDown.NumericUpDownSoap.Down(Web.UpDown.DownRequest request) {
            return base.Channel.Down(request);
        }
        
        public int Down(int current, string tag) {
            Web.UpDown.DownRequest inValue = new Web.UpDown.DownRequest();
            inValue.Body = new Web.UpDown.DownRequestBody();
            inValue.Body.current = current;
            inValue.Body.tag = tag;
            Web.UpDown.DownResponse retVal = ((Web.UpDown.NumericUpDownSoap)(this)).Down(inValue);
            return retVal.Body.DownResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.UpDown.DownResponse> Web.UpDown.NumericUpDownSoap.DownAsync(Web.UpDown.DownRequest request) {
            return base.Channel.DownAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.UpDown.DownResponse> DownAsync(int current, string tag) {
            Web.UpDown.DownRequest inValue = new Web.UpDown.DownRequest();
            inValue.Body = new Web.UpDown.DownRequestBody();
            inValue.Body.current = current;
            inValue.Body.tag = tag;
            return ((Web.UpDown.NumericUpDownSoap)(this)).DownAsync(inValue);
        }
    }
}
